config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'welcome#index'

  # API-Related routes
  namespace :api do
    namespace :v1 do
      resources :investigators, only: %i[index show]
    end
  end

  # Routes via resources (mostly)
  resources :users, only: %i[create delete] do
    resources :teams, only: %i[create new edit update destroy]
    get '/dashboard', to: 'users#show'
    post '/dashboard', to: 'users#show'
  end

  # Routes via handrolling for Auth
  get '/registration', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
    CARD_VARS = ["pack_name", "type_code", "subtype_code", "faction_name", "code", "name", "subname", "text", "quantity", "deck_limit", "traits", "flavor", "permanent", "double_sided", "back_text", "back_flavor", "imagesrc", "backimagesrc"]
    CARDS = []
    # map through payload, pull keys from hash if they are not in CARD_VARS constant.

    # # to be tested
    # def sort_investigators
    #     cards = CardFacade.all_cards
    #     cards.select do |card|
    #         card.type_code == "investigator"
    #     end
    # end

    # # to be tested
    # def sort_weaknesses
    #     cards = CardFacade.all_cards
    #     cards.select do |card|
    #         card.name != "Random Basic Weakness" && card.type_code == "treachery" && card.subtype_code == "basicweakness"
    #     end
    # end
    
    # # to be tested
    # def duplicate_weaknesses
    #     cards = CardFacade.all_cards
    #     cards.each do |card|
    #         if card.type_code == "treachery" && card.subtype_code == "basicweakness" && card.deck_limit == 2
    #             card.dup        
    #         end
    #     end
    # end
end

app/models/investigator.rb
# frozen_string_literal: true

class Investigator < ApplicationRecord
  belongs_to :team
  has_many :investigator_weaknesses
  has_many :weaknesses, through: :investigator_weaknesses
end

app/models/investigator_weakness.rb
# frozen_string_literal: true

class InvestigatorWeakness < ApplicationRecord
  belongs_to :investigator
  belongs_to :weakness
end

app/models/team.rb
# frozen_string_literal: true

class Team < ApplicationRecord
  has_many :user_teams
  has_many :users, through: :user_teams
  has_many :investigators
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :user_teams
  has_many :teams, through: :user_teams

  validates :username, uniqueness: true, presence: true

  has_secure_password
end

app/models/user_team.rb
# frozen_string_literal: true

class UserTeam < ApplicationRecord
  belongs_to :user
  belongs_to :team
end

app/models/weakness.rb
# frozen_string_literal: true

class Weakness < ApplicationRecord
  has_many :investigator_weaknesses
  has_many :investigators, through: :investigator_weaknesses
end

app/controllers/api/v1/cards_controller.rb
# frozen_string_literal: true

class Api::V1::CardsController < ApplicationController
  # GET /investigators or /investigators.json
  def index
    # if params[:type_code] == "investigator"
    #   investigator = CardFacade.all_cards
    #   render json: InvestigatorsSerializer
    # elsif params[:type_code] == "treachery" && params[:subtype_code] == "basicweakness"
    #   render json: WeaknessesSerializer.new()

  end

  # GET /investigators/1 or /investigators/1.json
  def show; end

  private

  def card_params
    params.permit(:type_code, :subtype_code, :name, :subname, :faction_name, :traits, :back_text, :back_flavor, :imagesrc, :backimagesrc)
  end
end

app/controllers/api/v1/investigators_controller.rb
class InvestigatorsController < ApplicationController

  # GET /investigators or /investigators.json
  def index; end

  # GET /investigators/1 or /investigators/1.json
  def show; end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end

  def require_current_user
    render file: '/public/404' unless current_user
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def create
    user = User.find_by(username: params[:username].downcase)
    if user&.authenticate(params[:password])
      session[:user_id] = user.id

      redirect_to user_dashboard_path(user.id), notice: 'Successfully logged in!'
    else
      redirect_to root_path, alert: 'Unable to log in, please try again.'
    end
  end
end

app/controllers/teams_controller.rb
# frozen_string_literal: true

class TeamsController < ApplicationController
  # before_action :set_team, only: %i[ show edit update destroy ]

  # GET /teams or /teams.json
  def index
    @teams = Team.all
  end

  # GET /teams/1 or /teams/1.json
  def show; end

  # GET /teams/new
  def new; end

  # GET /teams/1/edit
  def edit; end

  # POST /teams or /teams.json
  def create
    @user = current_user
    @team = Team.new(team_params)
  end

  # PATCH/PUT /teams/1 or /teams/1.json
  def update; end

  # DELETE /teams/1 or /teams/1.json
  def destroy; end

  private

  # Only allow a list of trusted parameters through.
  def team_params
    params.permit(:name, :campaign, :active)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  # GET /users or /users.json
  # Do not need an index

  # GET /users/1 or /users/1.json
  def show
    @user = current_user
  end

  # GET /users/new
  def new; end

  # GET /users/1/edit

  # POST /users or /users.json
  def create
    user = user_params
    new_user = User.new(user)
    if new_user.save
      # flash[:success] = "Successfully created account!"
      session[:user_id] = new_user.id
      redirect_to user_dashboard_path(new_user.id), notice: 'Successfully created account!'
    elsif user[:password] != user[:password_confirmation]
      redirect_to registration_path, alert: 'Passwords do not match.'
      # If the user
    elsif User.exists?(username: new_user.username)
      redirect_to registration_path, alert: 'Username taken.'
    else
      # flash[:error] = "Unable to register, please try again."
      redirect_to registration_path, alert: 'Unable to register, please try again.'
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy; end

  private

  # def existing_user
  #   User.where(new_user[:username] == user[:username])
  # end

  # Only allow a list of trusted parameters through.
  def user_params
    params.permit(:username, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/investigators_helper.rb
# frozen_string_literal: true

module InvestigatorsHelper
end

app/helpers/teams_helper.rb
# frozen_string_literal: true

module TeamsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/investigators/_form.html.erb
<%= form_with(model: investigator) do |form| %>
  <% if investigator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(investigator.errors.count, "error") %> prohibited this investigator from being saved:</h2>

      <ul>
        <% investigator.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="field">
    <%= form.label :deck_link %>
    <%= form.text_field :deck_link %>
  </div>

  <div class="field">
    <%= form.label :team_id %>
    <%= form.text_field :team_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/investigators/edit.html.erb
<h1>Editing Investigator</h1>

<%= render 'form', investigator: @investigator %>

<%= link_to 'Show', @investigator %> |
<%= link_to 'Back', investigators_path %>

app/views/investigators/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Investigators</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th>Deck link</th>
      <th>Team</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @investigators.each do |investigator| %>
      <tr>
        <td><%= investigator.name %></td>
        <td><%= investigator.image %></td>
        <td><%= investigator.deck_link %></td>
        <td><%= investigator.team_id %></td>
        <td><%= link_to 'Show', investigator %></td>
        <td><%= link_to 'Edit', edit_investigator_path(investigator) %></td>
        <td><%= link_to 'Destroy', investigator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Investigator', new_investigator_path %>

app/views/investigators/new.html.erb
<h1>New Investigator</h1>

<%= render 'form', investigator: @investigator %>

<%= link_to 'Back', investigators_path %>

app/views/investigators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @investigator.name %>
</p>

<p>
  <strong>Image:</strong>
  <%= @investigator.image %>
</p>

<p>
  <strong>Deck link:</strong>
  <%= @investigator.deck_link %>
</p>

<p>
  <strong>Team:</strong>
  <%= @investigator.team_id %>
</p>

<%= link_to 'Edit', edit_investigator_path(@investigator) %> |
<%= link_to 'Back', investigators_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ArkhamDownfall</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "shared/navbar" %>
    
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <style type="text/css">
      .alert-success{
        color: green;
      }
      .alert-danger{
        color: red;
      }
    </style>
    
    <div class="container">
      <%= yield %>
    </div>

    
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#"></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">My Home</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link active dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            My Teams
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<section class="py-3 text-center container">
<h1>Register for an Account</h1>
<br>
<%= form_with url: users_path, method: :post, local: true do |f| %>
<div class="row">
  <div class="col">
    <%= f.label :username%>
    <%= f.text_field :username %>
  </div>
    <div class="col">
      <%= f.label :password%>
      <%= f.password_field :password %>
    </div>
      <div class="col">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %>
      </div>
</div>
<br>
<%= f.submit 'Register' %>
<% end %>
<br>
<p><%= link_to "Already Registered? Log In Here!", root_path %></p>
</section>

app/views/users/show.html.erb
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<br>
  <h1 style="text-align: center">Welcome to Arkham Downfall!</h1>
<div id="welcome-message" style="margin: 20px auto; width: 600px; padding: 20px; background-color: #707070; border-radius: 10px; position: relative;" h4 class="text-light"></h4>
  <h4 style="text-align: center">A custom weakness generator for your Arkham teams</h4>
<section class="py-5 text-center container">
<div id="login-form">
  <%= form_with url: login_path, method: :post, local: true do |f| %>
  <div class="row">
    <div class="col">
      <%= f.label :username %>
      <%= f.text_field :username %><br>
    </div>
      <div class="col">
        <%= f.label :password %>
        <%= f.password_field :password %><br>
      </div>
  </div>
  <%= f.submit "Log In", :class => 'btn' %>
</div>
<br>
<%= link_to "Register for an Account", registration_path %>
</div>
<% end %>